name: intagramclone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11
  flutter_icons: ^1.1.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_messaging: ^11.2.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  intl: ^0.17.0
  device_info_plus: ^3.2.2
  flutter_local_notifications: ^9.4.0
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.2
  share_plus: ^4.0.3
  http: ^0.13.4
  get: ^4.6.1
  firebase_crashlytics: ^2.8.4
  # for dynmaic lnk uchun
  firebase_dynamic_links: ^4.3.1
  firebase_remote_config: ^2.0.12
  # increption
  encrypt: ^5.0.1
  # asymmetric
  crypton: ^2.0.5
  rsa_encrypt: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Billabong
      fonts:
       - asset: assets/fonts/billabong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
